### ISSUE TITLE
Prop type validation

### ISSUE THREAD

**Issue by shankie-codes** [fbonesso/react-native-masked-input#1]
I'm trying to use your component, but it's failing prop type validation. For some reason, the prop type validation for props, e.g. `maskType` is set to object, even though the component wants a string. Is there any reason for this?

**Comment by isaldin** [comment]
@shankiesan it causes because in lib set **maskType: React.PropTypes.object** instead of **maskType: React.PropTypes.string**

**Comment by shankie-codes** [comment]
Yep, understand that @isaldin – but I was just wondering why that was the case @fbonesso . I'm happy to submit a PR if it should be `React.PropTypes.string`

**Comment by fbonesso** [comment]
@shankiesan Yeah, should be `React.PropTypes.string`. If you could submit a PR would be great! Thanks!

**Comment by gaboAcosta** [comment]
I see this closed, if you merged it into a PR can you release a new version in npm? Thanks!

**Comment by robinheinze** [comment]
@fbonesso Looks like this PR never made it to npm. Would it be possible to publish a new version? Thanks!
