### ISSUE TITLE
Failed prop type: Invalid prop `maskType` of type `string` supplied to `MaskedInput

### ISSUE THREAD

**Issue by bitcoinvsalts** [fbonesso/react-native-masked-input#3]
Warning: Failed prop type: Invalid prop `maskType` of type `string` supplied to `MaskedInput`, expected `object`.
[exp]     in MaskedInput (created by GetOfferPrices)
[exp]     in GetOfferPrices (created by InqueryScreen)
[exp]     in RCTView (created by View)

**Comment by sortinousn** [comment]
Experiencing the same.

**Comment by jderose9** [comment]
same here.

**Comment by tobob** [comment]
use latest master instead of npm latest version

```
    "react-native-masked-input": "fbonesso/react-native-masked-input",
```
